
services: 
  mysql_knex:
    env_file:
      - .env
    container_name: mysql_knex
    hostname: mysql_knex
    image: mysql:8.0  # DICA: Use a versão 8.0 que é a mais estável para cursos
    restart: always
    command:
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_force_recovery=0
    volumes: 
      - C:\Users\jean_bortolon\Desktop\backup_mysql_docker:/var/lib/mysql
    ports:
      - 3307:3306
    environment:
      TZ: America/Sao_Paulo