'''FAÇA UM LAÇO WHILE PARA CONCATENAR UM ASTERISCO A CADA LETRA DO NOME'''

nome = input('Digite seu nome:')
tamanho = 0
nova_string = ''

''' ENQUANTO TAMANHO FOR MENOR QUE O TAMANHO DO NOME UMA NOVA STRING
VAI RECEBER UM SOMATORIO DE CADA LETRA DA STRING NOME PASSANDO POR INDICE
A INDICE CONTROLADOR PELO TAMANHO SENDO CONCATENADO AO ASTERISCO
O TAMANHO É INCREMENTADO APÓS ESSA ATRIBUIÇÃO E A STRING FINAL É 
PRINTADA CONCATENANDO O ULTIMO ASTERISCO'''
while tamanho < len(nome):
    nova_string += '*' + nome[tamanho] 
    tamanho += 1
print(f'{nova_string}*')